spring.profiles.active=dev

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuracion para manejar archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Hibernate settings
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# Reduce Hibernate logging verbosity
logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type=INFO

# Disable Open-in-view
spring.jpa.open-in-view=false

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
management.endpoints.web.exposure.include=*

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Server Port
server.port=8080

spring.main.allow-circular-references=true

logging.level.root=INFO
logging.level.com.example.gestion_curriculums0=DEBUG
logging.file.name=gestion_curriculums0.log

spring.mvc.static-path-pattern=/frontend/**
spring.resources.static-locations=classpath:/frontend/

# Email configuration
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}
spring.mail.properties.mail.smtp.writetimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT}
