# Configuración específica para el perfil "prod" (producción)
# URL base de la aplicación cuando se ejecuta en un entorno de producción
app.baseUrl=https://gestionatuscv.es
app.cors.allowed-origins=https://gestionatuscv.es,https://gestionatuscvs-production.up.railway.app

# app.baseUrl: Define la URL base para la aplicación cuando se está ejecutando en un entorno de producción.
# En este caso, la URL apunta al dominio público de la aplicación (https://gestionatuscv.es).
# Esto asegura que las solicitudes se realicen a la versión en vivo de la aplicación cuando está desplegada en producción.
