# Configuración de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración para manejar archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Configuración de Hibernate
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# Reducir la verbosidad del logging de Hibernate
logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type=INFO

# Deshabilitar Open-in-view
spring.jpa.open-in-view=false

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
management.endpoints.web.exposure.include=*

# Configuración de JWT
jwt.secret=${JWT_SECRET}

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Puerto del servidor
server.port=${PORT:8080}

# Permitir referencias circulares
spring.main.allow-circular-references=true

logging.level.root=INFO
logging.level.com.example.gestion_curriculums0=DEBUG
logging.file.name=gestion_curriculums0.log

# Configuración de correo electrónico
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gestionatuscv@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
logging.level.org.springframework.mail=DEBUG

# Configuración de HikariCP (pool de conexiones)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.connection-timeout=30000
