# Configuración específica para el perfil "deb" (desarrollo)
# URL base de la aplicación cuando se ejecuta en un entorno de desarrollo local
app.baseUrl=http://localhost:8080
app.cors.allowed-origins=http://localhost:8080,http://localhost:8000

# app.baseUrl: Define la URL base para la aplicación cuando se está ejecutando en un entorno de desarrollo.
# En este caso, la URL apunta al servidor local en el puerto 8080, que es típico para entornos de desarrollo y el
# que tengo por defecto con xampp.
# Esto permite que solicitudes de la aplicación se hagan al servidor local mientras desarrollo y pruebo funcionalidades
